### ISSUE TITLE
Problema installazione estensione

### ISSUE THREAD

**Issue by CiroBoxHub** [OpenCode/vsc-odoo-development#4]
All'installazione dell'estensione viene visualizzato questo errore:

![Schermata da 2021-02-16 11-28-06](https://user-images.githubusercontent.com/16084466/108051431-2cb74b00-704b-11eb-84cb-b66779a6de69.png)

Versione VSCodium March 2019 (version 1.33)

**Comment by OpenCode** [comment]
Ciao @CiroBoxHub,

l'estensione richiede che il modo di Visual Studio Code (o derivate) sia almeno quello della versione 1.43.0 o superiore.

TI consiglio di aggiornare la tua versione di VSCodium all'ultima disponibile che, al momento, è la 1.52.1

Per avere il software aggioranto puoi installarlo tramite Flatpack: https://flathub.org/apps/details/com.vscodium.codium
